name: My First Github Action
on: [push]
jobs:
# job runs parallely but steps don't.
# Jobs do not necessarily execute in sequence although array elements(steps) do .
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world!!"
      - run: echo "this is step no.2"
# You can have multiple jobs.
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
          #property
          with: 
            #I want node 14 cloned into my repository
            node-version: '14.17.0' 
      - run: node -v